version: "3"
services:
  batch_convert:
    container_name: batch_convert
    build: .
    environment:
      - PUID=1000 # use whatever user you need
      - PGID=1000 # use whatever group you need
    volumes:
      - /path/to/source/directory:/app/source:rw
      - /path/to/destination/directory:/app/export:rw
    