version: "3"
services:
  batch_convert:
    container_name: batch_convert
    build: .
    environment:
      - PUID=1000 # use whatever user you need
      - PGID=1000 # use whatever group you need
      - SOURCE_FILE_CLEANUP='true'
      - FILETYPES="mkv,mov,mp4" # must be a string of file types split by commas and no spaces
    volumes:
      - /path/to/source/directory:/app/source:rw
      - /path/to/destination/directory:/app/export:rw
    